version: '3.8'
services:
  assinatura-app:
    build: .
    ports:
      - "85:3000"
    volumes:
      - ./frontend:/app/frontend
      - ./backend:/app/backend
      - ./assets:/app/assets
    command: node backend/server.js
